/**
 * Settlement lookup for the «Населённый пункт» field of the sign-up form
 * (Issue #83). The directory (`src/data/settlements.json`, generated by
 * `scripts/generate-settlements.mjs` from ОКТМО) lists RF cities and
 * urban-type settlements; a pick fills the platform's separate `city` and
 * `region` answers, and anything the directory does not resolve stays free text.
 *
 * Matching is deliberately conservative — a wrong silent pick would put a
 * participant in the wrong region, which is worse than asking for the region:
 * the full option label, a bare name found in exactly one region, or (on
 * change/blur only) a prefix of four letters or more shared by no other name.
 *
 * `status` is what the form decides the «Регион» field on, WHILE the
 * participant types: the layout must settle before focus or a press leaves the
 * field, so the decision cannot wait for blur.
 */

/** The shipped shape: region names once, places as [name, region index]. */
export interface SettlementDirectory {
  regions: string[];
  places: [string, number][];
}

export interface Settlement {
  name: string;
  region: string;
  /** What the datalist shows and the input keeps: «Химки — Московская область». */
  label: string;
}

export const MIN_PREFIX = 4;

/** «Москва» for a federal city — «Москва — г. Москва» would say it twice. */
export function settlementLabel(name: string, region: string): string {
  return region === `г. ${name}` ? name : `${name} — ${region}`;
}

export function expandDirectory({ regions, places }: SettlementDirectory): Settlement[] {
  return places.map(([name, i]) => {
    const region = regions[i];
    if (region === undefined) throw new Error(`settlements: no region #${i} for «${name}»`);
    return { name, region, label: settlementLabel(name, region) };
  });
}

// «г.», «пгт», «пос.» … as people type them before a name. A prefix needs a dot
// or a space after it, so «Гатчина» and «Пушкин» keep their first letter.
const TYPE_PREFIX = /^(?:г|гор|город|пгт|рп|кп|дп|гп|п|пос|поселок)(?:\.\s*|\s+)(?=\S)/;
// Between name and region: a comma, or a dash with a space on either side. A
// hyphen inside a name («Ростов-на-Дону») has neither and is left alone.
const SEPARATOR = /\s*,\s*|\s+[-–—]\s*|\s*[-–—]\s+/g;

/** Comparison key: case, ё/е, spacing, separators and a type prefix ignored. */
export function normalisePlace(value: string): string {
  return value
    .toLocaleLowerCase('ru')
    .replace(/ё/g, 'е')
    .trim()
    .replace(/\s+/g, ' ')
    .replace(SEPARATOR, ' - ')
    .replace(TYPE_PREFIX, '');
}

/**
 * Where typed text stands against the directory:
 * - `empty` — nothing typed;
 * - `match` — resolves to one entry (a prefix included);
 * - `ambiguous` — exactly a name found in several regions, so the region must
 *   be picked from the list or given separately;
 * - `unknown` — no entry's name or label begins with it: a place outside the
 *   directory;
 * - `pending` — still a beginning of more than one entry; typing decides.
 */
export type SettlementStatus =
  | { kind: 'empty' }
  | { kind: 'match'; settlement: Settlement }
  | { kind: 'ambiguous' }
  | { kind: 'unknown' }
  | { kind: 'pending' };

export interface SettlementIndex {
  entries: readonly Settlement[];
  match(typed: string, options?: { allowPrefix?: boolean }): Settlement | null;
  status(typed: string): SettlementStatus;
}

export function createSettlementIndex(entries: readonly Settlement[]): SettlementIndex {
  const keyed = entries.map((entry) => ({
    entry,
    label: normalisePlace(entry.label),
    name: normalisePlace(entry.name),
  }));
  const only = <T>(hits: T[]): T | null => (hits.length === 1 ? hits[0] : null);

  return {
    entries,
    match(typed, { allowPrefix = true } = {}) {
      const needle = normalisePlace(typed);
      if (needle === '') return null;
      const byLabel = keyed.find((k) => k.label === needle);
      if (byLabel) return byLabel.entry;
      const byName = keyed.filter((k) => k.name === needle);
      if (byName.length > 0) return only(byName)?.entry ?? null;
      if (!allowPrefix || needle.length < MIN_PREFIX) return null;
      return only(keyed.filter((k) => k.name.startsWith(needle)))?.entry ?? null;
    },
    status(typed) {
      const needle = normalisePlace(typed);
      if (needle === '') return { kind: 'empty' };
      const settlement = this.match(typed);
      if (settlement) return { kind: 'match', settlement };
      if (keyed.filter((k) => k.name === needle).length > 1) return { kind: 'ambiguous' };
      const open = keyed.some((k) => k.name.startsWith(needle) || k.label.startsWith(needle));
      return { kind: open ? 'pending' : 'unknown' };
    },
  };
}

/**
 * What the combobox filters the directory's NAMES on: the comparison key up to
 * a typed separator, so «г. Кировск — Мур…» still lists every Кировск and the
 * region part picks among them by eye.
 */
export function settlementNameQuery(typed: string): string {
  return normalisePlace(typed).split(' - ')[0] ?? '';
}
